name: Terraform CI 

on:  # 트리거 조건
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs: # GitHub Actions가 실행될 환경
  terraform:
    name: Terraform Plan 
    runs-on: ubuntu-latest


    permissions:
      pull-requests: write  # PR에 코멘트 달기 위해 필요

    steps: # 실제 실행 단계들
      - name: Checkout repository
        uses: actions/checkout@v4 # checkout - GitHub 코드 내려받기
        # GitHub Actions가 이 레포의 코드를 가상머신에 다운르도해서 사용할 수 있게 함(git clone 같은 역할)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -recursive # recursive - 하위 dir까지 전부 검사


      - name: Terraform Init
        run: terraform init -backend=false # -backend=false -> s3같은 리모트 백엔드 연결 생략하고 로컬만 사용(CI에서는 보통 이렇게 함)


      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -no-color \
            -var='aws_region=ap-northeast-2' \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='public_subnet_cidrs=["10.0.0.0/24","10.0.10.0/24"]' \
            -var='private_subnet_cidrs=["10.0.1.0/24","10.0.11.0/24"]' \
            -var='private_subnet_2_cidrs=["10.0.2.0/24","10.0.12.0/24"]' \
            -var='private_rds_subnet_cidrs=["10.0.3.0/24","10.0.13.0/24"]' \
            -var='availability_zones=["ap-northeast-2a","ap-northeast-2c"]' \
            -var='mgmt_ami=ami-0662f4965dfc70aca' \
            -var='mgmt_instance_type=t2.micro' \
            -var='rds_identifier=cgc-pnp-rds' \
            -var='rds_engine=mysql' \
            -var='rds_engine_version=8.0.41' \
            -var='rds_instance_class=db.t3.micro' \
            -var='rds_allocated_storage=20' \
            -var='rds_username=pnp' \
            -var='rds_password=${{ secrets.RDS_PASSWORD }}' \
            -var='rds_multi_az=true' \
            -var='rds_publicly_accessible=false' \
