name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types: 
      - completed

jobs:
  terraform-apply:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-2

      - name: Terraform Init
        run: terraform init -input=false -reconfigure
    
      - name: Terraform Apply
        run: |
          terraform apply \
            -var='aws_region=ap-northeast-2' \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='public_subnet_cidrs=["10.0.0.0/24","10.0.10.0/24"]' \
            -var='private_subnet_cidrs=["10.0.1.0/24","10.0.11.0/24"]' \
            -var='private_subnet_2_cidrs=["10.0.2.0/24","10.0.12.0/24"]' \
            -var='private_rds_subnet_cidrs=["10.0.3.0/24","10.0.13.0/24"]' \
            -var='availability_zones=["ap-northeast-2a","ap-northeast-2c"]' \
            -var='mgmt_ami=ami-0662f4965dfc70aca' \
            -var='mgmt_instance_type=t2.micro' \
            -var='rds_identifier=cgc-pnp-rds' \
            -var='rds_engine=mysql' \
            -var='rds_engine_version=8.0.41' \
            -var='rds_instance_class=db.t3.micro' \
            -var='rds_allocated_storage=20' \
            -var='rds_username=pnp' \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}" \
            -var='rds_multi_az=true' \
            -var='rds_publicly_accessible=false' \
            --auto-approve
