name: Terraform CD

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest


    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6


      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -var-file="terraform.tfvars" --auto-approve
