name: Terraform CI/CD - Base

on:
  push:
    paths:
      - 'terraform/base/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'terraform/base/**'
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Apply - Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Terraform Init (base)
        run: terraform init -input=false -upgrade -reconfigure
        working-directory: terraform/base

      - name: Terraform Plan (base)
        run: |
          terraform plan \
            -no-color \
            -var='aws_region=ap-northeast-2' \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='public_subnet_cidrs=["10.0.0.0/24","10.0.10.0/24"]' \
            -var='private_subnet_cidrs=["10.0.1.0/24","10.0.11.0/24"]' \
            -var='private_subnet_2_cidrs=["10.0.2.0/24","10.0.12.0/24"]' \
            -var='private_rds_subnet_cidrs=["10.0.3.0/24","10.0.13.0/24"]' \
            -var='availability_zones=["ap-northeast-2a","ap-northeast-2c"]' \
            -var='mgmt_ami=ami-0662f4965dfc70aca' \
            -var='mgmt_instance_type=t2.micro' \
            -var='rds_identifier=cgc-pnp-rds' \
            -var='rds_engine=mysql' \
            -var='rds_engine_version=8.0.41' \
            -var='rds_instance_class=db.t3.micro' \
            -var='rds_allocated_storage=20' \
            -var='rds_username=pnp' \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}" \
            -var='rds_multi_az=true' \
            -var='rds_publicly_accessible=false'
        working-directory: terraform/base

      - name: Terraform Apply (base)
        run: |
          terraform apply -auto-approve \
            -var='aws_region=ap-northeast-2' \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='public_subnet_cidrs=["10.0.0.0/24","10.0.10.0/24"]' \
            -var='private_subnet_cidrs=["10.0.1.0/24","10.0.11.0/24"]' \
            -var='private_subnet_2_cidrs=["10.0.2.0/24","10.0.12.0/24"]' \
            -var='private_rds_subnet_cidrs=["10.0.3.0/24","10.0.13.0/24"]' \
            -var='availability_zones=["ap-northeast-2a","ap-northeast-2c"]' \
            -var='mgmt_ami=ami-0662f4965dfc70aca' \
            -var='mgmt_instance_type=t2.micro' \
            -var='rds_identifier=cgc-pnp-rds' \
            -var='rds_engine=mysql' \
            -var='rds_engine_version=8.0.41' \
            -var='rds_instance_class=db.t3.micro' \
            -var='rds_allocated_storage=20' \
            -var='rds_username=pnp' \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}" \
            -var='rds_multi_az=true' \
            -var='rds_publicly_accessible=false'
        working-directory: terraform/base

